<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：$BE$AllEnumMD.php.tt
//     生成日期：2019-09-12 14:15:23
// </auto-generated>
//------------------------------------------------------------------------------	

namespace comMoerlongBL\mD\metadata;

/**
 * BE下所有元数据 
 */
class MDComponentMDFactory
{
	
	public static function getAllEnumJSON(){
		return '[{"name":"EnumUIMDElementType","fullName":"App\\Http\\Modules\\MDComponent\\GeneratedCodes\\Enum\\EnumUIMDElementType","displayName":"UI元数据类型","description":"UI元数据类型","items": [{"value":"1","name":"page","displayName":"页面","description":"页面"},{"value":"2","name":"menu","displayName":"菜单","description":"菜单"},{"value":"4","name":"button","displayName":"按钮","description":"按钮"}]}]';
	}
}

