<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 教育背景
 * 教育背景
 * 
 */
class EnumEduBackground
{
	const Description=array('1'=>'大专以下','2'=>'大专','4'=>'本科','8'=>'硕士及其以上');
		
	/**
     * 大专以下
	 * 大专以下（默认））
     */
    const CollegeOrBelow = 1;	
		
	/**
     * 大专
	 * 大专
     */
    const College = 2;	
		
	/**
     * 本科
	 * 本科
     */
    const Undergraduate = 4;	
		
	/**
     * 硕士及其以上
	 * 硕士及其以上
     */
    const MasterOrAbove = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
