<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 行业类别
 * 行业类别
 * 
 */
class EnumIndustryCategory
{
	const Description=array('1'=>'公务员（非公检法）','2'=>'公检法','4'=>'C类','8'=>'事业单位','16'=>'国有企业、银行','32'=>'上市公司、世界500强','64'=>'投资公司','128'=>'二手车交易','256'=>'其他');
		
	/**
     * 公务员（非公检法）
	 * 公务员（非公检法）
     */
    const ClassA = 1;	
		
	/**
     * 公检法
	 * 公检法
     */
    const ClassB = 2;	
		
	/**
     * C类
	 * 其他行业
     */
    const ClassC = 4;	
		
	/**
     * 事业单位
	 * 事业单位
     */
    const ClassD = 8;	
		
	/**
     * 国有企业、银行
	 * 国有企业、银行
     */
    const ClassE = 16;	
		
	/**
     * 上市公司、世界500强
	 * 上市公司、世界500强
     */
    const ClassF = 32;	
		
	/**
     * 投资公司
	 * 投资公司
     */
    const ClassG = 64;	
		
	/**
     * 二手车交易
	 * 二手车交易
     */
    const ClassH = 128;	
		
	/**
     * 其他
	 * 其他
     */
    const ClassI = 256;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
