<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 还款方式
 * 还款方式
 * 
 */
class EnumRepayment
{
	const Description=array('1'=>'随借随还','2'=>'先息后本','4'=>'等额本息','8'=>'等额本金','16'=>'循环贷','32'=>'计划还款','64'=>'气球贷');
		
	/**
     * 随借随还
	 * 随借随还
     */
    const RepayAnyTime = 1;	
		
	/**
     * 先息后本
	 * 先息后本
     */
    const BeforInstallment = 2;	
		
	/**
     * 等额本息
	 * 等额本息
     */
    const FixedInstallment = 4;	
		
	/**
     * 等额本金
	 * 等额本金
     */
    const FixedPrincipal = 8;	
		
	/**
     * 循环贷
	 * 循环贷
     */
    const RevolvingLoan = 16;	
		
	/**
     * 计划还款
	 * 计划还款
     */
    const PlannedRepayment = 32;	
		
	/**
     * 气球贷
	 * 气球贷
     */
    const BalloonLoan = 64;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
