<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 车辆用途
 * 车辆用途
 * 
 */
class EnumVehicleUse
{
	const Description=array('1'=>'自用','2'=>'运营');
		
	/**
     * 自用
	 * 自用
     */
    const SelfUse = 1;	
		
	/**
     * 运营
	 * 运营
     */
    const Operation = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
