<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-04 10:22:59
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 贷款机构
 * 贷款机构
 * 
 */
class EnumLoanInstitution
{
	const description=array('1'=>'中国银行','2'=>'农业银行','4'=>'工商银行','8'=>'建设银行','16'=>'交通银行','32'=>'招商银行','64'=>'光大银行','128'=>'兴业银行','256'=>'平安银行','512'=>'中信银行','1024'=>'浦发银行','2048'=>'华夏银行','4096'=>'广发银行','8192'=>'天府银行','16384'=>'浙商银行','32768'=>'渤海银行','65536'=>'民生银行','131072'=>'成都银行','262144'=>'攀枝花商业银行','524288'=>'其它银行');
		
	/**
     * 中国银行
	 * 中国银行（默认）
     */
    const bOC = 1;	
		
	/**
     * 农业银行
	 * 农业银行
     */
    const aBC = 2;	
		
	/**
     * 工商银行
	 * 工商银行
     */
    const iCBC = 4;	
		
	/**
     * 建设银行
	 * 建设银行
     */
    const cCB = 8;	
		
	/**
     * 交通银行
	 * 交通银行
     */
    const bCM = 16;	
		
	/**
     * 招商银行
	 * 招商银行
     */
    const cMB = 32;	
		
	/**
     * 光大银行
	 * 光大银行
     */
    const cEB = 64;	
		
	/**
     * 兴业银行
	 * 兴业银行
     */
    const cIB = 128;	
		
	/**
     * 平安银行
	 * 平安银行
     */
    const pAB = 256;	
		
	/**
     * 中信银行
	 * 中信银行
     */
    const cITIC = 512;	
		
	/**
     * 浦发银行
	 * 浦发银行
     */
    const sPD = 1024;	
		
	/**
     * 华夏银行
	 * 华夏银行
     */
    const hXB = 2048;	
		
	/**
     * 广发银行
	 * 广发银行
     */
    const cGB = 4096;	
		
	/**
     * 天府银行
	 * 天府银行
     */
    const tFB = 8192;	
		
	/**
     * 浙商银行
	 * 浙商银行
     */
    const cZB = 16384;	
		
	/**
     * 渤海银行
	 * 渤海银行
     */
    const cBH = 32768;	
		
	/**
     * 民生银行
	 * 民生银行
     */
    const cMBC = 65536;	
		
	/**
     * 成都银行
	 * 成都银行
     */
    const bOCD = 131072;	
		
	/**
     * 攀枝花商业银行
	 * 攀枝花商业银行
     */
    const pZHCCB = 262144;	
		
	/**
     * 其它银行
	 * 其它银行
     */
    const other = 524288;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumLoanInstitution","fullName":"App\\Http\\Modules\\UMComponent\\GeneratedCodes\\Enum\\EnumLoanInstitution","displayName":"贷款机构","description":"贷款机构","items": [{"value":"1","name":"bOC","displayName":"中国银行","description":"中国银行（默认）"},{"value":"2","name":"aBC","displayName":"农业银行","description":"农业银行"},{"value":"4","name":"iCBC","displayName":"工商银行","description":"工商银行"},{"value":"8","name":"cCB","displayName":"建设银行","description":"建设银行"},{"value":"16","name":"bCM","displayName":"交通银行","description":"交通银行"},{"value":"32","name":"cMB","displayName":"招商银行","description":"招商银行"},{"value":"64","name":"cEB","displayName":"光大银行","description":"光大银行"},{"value":"128","name":"cIB","displayName":"兴业银行","description":"兴业银行"},{"value":"256","name":"pAB","displayName":"平安银行","description":"平安银行"},{"value":"512","name":"cITIC","displayName":"中信银行","description":"中信银行"},{"value":"1024","name":"sPD","displayName":"浦发银行","description":"浦发银行"},{"value":"2048","name":"hXB","displayName":"华夏银行","description":"华夏银行"},{"value":"4096","name":"cGB","displayName":"广发银行","description":"广发银行"},{"value":"8192","name":"tFB","displayName":"天府银行","description":"天府银行"},{"value":"16384","name":"cZB","displayName":"浙商银行","description":"浙商银行"},{"value":"32768","name":"cBH","displayName":"渤海银行","description":"渤海银行"},{"value":"65536","name":"cMBC","displayName":"民生银行","description":"民生银行"},{"value":"131072","name":"bOCD","displayName":"成都银行","description":"成都银行"},{"value":"262144","name":"pZHCCB","displayName":"攀枝花商业银行","description":"攀枝花商业银行"},{"value":"524288","name":"other","displayName":"其它银行","description":"其它银行"}]}';
	}
}
