<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 名下汽车
 * 名下汽车
 * 
 */
class EnumOwnerVehicle
{
	const Description=array('1'=>'没有','2'=>'1辆','4'=>'2辆及以上');
		
	/**
     * 没有
	 * 没有
     */
    const None = 1;	
		
	/**
     * 1辆
	 * 1辆
     */
    const One = 2;	
		
	/**
     * 2辆及以上
	 * 2辆及以上
     */
    const TwoOrAbove = 4;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
