<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 证件类型
 * 证件类型
 * 
 */
class EnumCertificateType
{
	const Description=array('1'=>'身份证','2'=>'驾驶证','4'=>'军官证','8'=>'行驶证','16'=>'护照');
		
	/**
     * 身份证
	 * 身份证
     */
    const IdCard = 1;	
		
	/**
     * 驾驶证
	 * 驾驶证
     */
    const Driver = 2;	
		
	/**
     * 军官证
	 * 军官证
     */
    const OfficerCard = 4;	
		
	/**
     * 行驶证
	 * 行驶证
     */
    const Vehicle = 8;	
		
	/**
     * 护照
	 * 护照
     */
    const Passport = 16;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
