<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-04-26 11:41:27
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 车辆用途
 * 车辆用途
 * 
 */
class EnumVehicleUse
{
	const description=array('1'=>'自用','2'=>'运营');
		
	/**
     * 自用
	 * 自用
     */
    const selfUse = 1;	
		
	/**
     * 运营
	 * 运营
     */
    const operation = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumVehicleUse","fullName":"App\\Http\\Modules\\UMComponent\\GeneratedCodes\\Enum\\EnumVehicleUse","displayName":"车辆用途","description":"车辆用途","items": [{"value":"1","name":"selfUse","displayName":"自用","description":"自用"},{"value":"2","name":"operation","displayName":"运营","description":"运营"}]}';
	}
}
