<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-01 11:29:44
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 民族
 * 民族
 * 
 */
class EnumEthnicity
{
	const description=array('1'=>'其他','2'=>'汉族','3'=>'藏族');
		
	/**
     * 其他
	 * 其他
     */
    const other = 1;	
		
	/**
     * 汉族
	 * 汉族
     */
    const han = 2;	
		
	/**
     * 藏族
	 * 藏族
     */
    const zang = 3;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumEthnicity","fullName":"App\\Http\\Modules\\UMComponent\\GeneratedCodes\\Enum\\EnumEthnicity","displayName":"民族","description":"民族","items": [{"value":"1","name":"other","displayName":"其他","description":"其他"},{"value":"2","name":"han","displayName":"汉族","description":"汉族"},{"value":"3","name":"zang","displayName":"藏族","description":"藏族"}]}';
	}
}
