<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 民族
 * 民族
 * 
 */
class EnumEthnicity
{
	const Description=array('1'=>'其他','2'=>'汉族','3'=>'藏族');
		
	/**
     * 其他
	 * 其他
     */
    const Other = 1;	
		
	/**
     * 汉族
	 * 汉族
     */
    const Han = 2;	
		
	/**
     * 藏族
	 * 藏族
     */
    const Zang = 3;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
