<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 车辆号牌区号
 * 车辆号牌区号
 * 
 */
class EnumVNAreaCode
{
	const Description=array('1'=>'京','2'=>'津','3'=>'冀','4'=>'晋','5'=>'蒙','6'=>'辽','7'=>'吉','8'=>'黑','9'=>'沪','10'=>'苏','11'=>'浙','12'=>'皖','13'=>'闽','14'=>'赣','15'=>'鲁','16'=>'豫','17'=>'鄂','18'=>'湘','19'=>'粤','20'=>'桂','21'=>'琼','22'=>'渝','23'=>'川','24'=>'贵','25'=>'云','26'=>'藏','27'=>'陕','28'=>'甘','29'=>'青','30'=>'宁','31'=>'新');
		
	/**
     * 京
	 * 北京
     */
    const Beijing = 1;	
		
	/**
     * 津
	 * 天津
     */
    const Tianjin = 2;	
		
	/**
     * 冀
	 * 河北
     */
    const Hebei = 3;	
		
	/**
     * 晋
	 * 山西省
     */
    const Shanxi = 4;	
		
	/**
     * 蒙
	 * 内蒙古自治区
     */
    const Neimenggu = 5;	
		
	/**
     * 辽
	 * 辽宁省
     */
    const Liaoning = 6;	
		
	/**
     * 吉
	 * 吉林省
     */
    const Jilin = 7;	
		
	/**
     * 黑
	 * 黑龙江省
     */
    const Heilongjiang = 8;	
		
	/**
     * 沪
	 * 上海市
     */
    const Shanghai = 9;	
		
	/**
     * 苏
	 * 江苏省
     */
    const Jiangsu = 10;	
		
	/**
     * 浙
	 * 浙江省
     */
    const Zhejiang = 11;	
		
	/**
     * 皖
	 * 安徽省
     */
    const Anhui = 12;	
		
	/**
     * 闽
	 * 福建省
     */
    const Fujian = 13;	
		
	/**
     * 赣
	 * 江西省
     */
    const Jiangxi = 14;	
		
	/**
     * 鲁
	 * 山东省
     */
    const Shandong = 15;	
		
	/**
     * 豫
	 * 河南省
     */
    const Henan = 16;	
		
	/**
     * 鄂
	 * 湖北省
     */
    const Hubei = 17;	
		
	/**
     * 湘
	 * 湖南省
     */
    const Hunan = 18;	
		
	/**
     * 粤
	 * 广东省
     */
    const Guangdong = 19;	
		
	/**
     * 桂
	 * 广西壮族自治区
     */
    const Guangxi = 20;	
		
	/**
     * 琼
	 * 海南省
     */
    const Hainan = 21;	
		
	/**
     * 渝
	 * 重庆市
     */
    const Chongqing = 22;	
		
	/**
     * 川
	 * 四川省
     */
    const Sichuan = 23;	
		
	/**
     * 贵
	 * 贵州省
     */
    const Guizhou = 24;	
		
	/**
     * 云
	 * 云南省
     */
    const Yunnan = 25;	
		
	/**
     * 藏
	 * 西藏自治区
     */
    const Xizang = 26;	
		
	/**
     * 陕
	 * 陕西省
     */
    const Shaanxi = 27;	
		
	/**
     * 甘
	 * 甘肃省
     */
    const Gansu = 28;	
		
	/**
     * 青
	 * 青海省
     */
    const Qinghai = 29;	
		
	/**
     * 宁
	 * 宁夏回族自治区
     */
    const Ningxia = 30;	
		
	/**
     * 新
	 * 新疆维吾尔自治区
     */
    const Xinjiang = 31;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
