<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * APP应用联系方式
 * APP应用联系方式
 * 
 */
class EnumAPPContact
{
	const Description=array('1'=>'qq号','2'=>'微信','4'=>'支付宝账号');
		
	/**
     * qq号
	 * qq号
     */
    const QQ = 1;	
		
	/**
     * 微信
	 * 微信
     */
    const Wexin = 2;	
		
	/**
     * 支付宝账号
	 * 支付宝账号
     */
    const Alipay = 4;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
