<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 土地性质
 * 土地性质
 * 
 */
class EnumLandNature
{
	const Description=array('1'=>'出让','2'=>'划拨');
		
	/**
     * 出让
	 * 出让（默认）
     */
    const Transfer = 1;	
		
	/**
     * 划拨
	 * 划拨
     */
    const Allocation = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
