<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 职业身份
 * 职业身份
 * 
 */
class EnumProfessionalIdentity
{
	const Description=array('1'=>'上班族','2'=>'个体户','4'=>'企业主');
		
	/**
     * 上班族
	 * 上班族
     */
    const OfficeWoker = 1;	
		
	/**
     * 个体户
	 * 个体户
     */
    const SelfEmployed = 2;	
		
	/**
     * 企业主
	 * 企业主
     */
    const BusinessOwner = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
