<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 名下房产
 * 名下房产
 * 
 */
class EnumOwnerHouseProperty
{
	const Description=array('1'=>'没有房产','2'=>'一套房产','4'=>'两套及其以上');
		
	/**
     * 没有房产
	 * 没有房产
     */
    const None = 1;	
		
	/**
     * 一套房产
	 * 一套房产
     */
    const One = 2;	
		
	/**
     * 两套及其以上
	 * 两套及其以上
     */
    const TwoOrAbove = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
