<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 房产类型
 * 房产类型
 * 
 */
class EnumHousePropertyType
{
	const Description=array('1'=>'住宅','2'=>'70年公寓','4'=>'40年公寓','8'=>'40年商铺','16'=>'40年办公','32'=>'别墅','64'=>'其它');
		
	/**
     * 住宅
	 * 住宅
     */
    const Residential = 1;	
		
	/**
     * 70年公寓
	 * 70年公寓
     */
    const Apartment70 = 2;	
		
	/**
     * 40年公寓
	 * 40年公寓
     */
    const Apartment40 = 4;	
		
	/**
     * 40年商铺
	 * 40年商铺
     */
    const Pavement40 = 8;	
		
	/**
     * 40年办公
	 * 40年办公
     */
    const Office40 = 16;	
		
	/**
     * 别墅
	 * 别墅
     */
    const Villa = 32;	
		
	/**
     * 其它
	 * 其它
     */
    const Other = 64;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
