<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 客户类型
 * 客户类型
 * 
 */
class EnumCustomerType
{
	const Description=array('1'=>'潜在客户','2'=>'意向客户');
		
	/**
     * 潜在客户
	 * 潜在客户
     */
    const Potential = 1;	
		
	/**
     * 意向客户
	 * 意向客户
     */
    const Intentional = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
