<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-22 16:41:33
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 贷款期数
 * 贷款期数
 * 
 */
class EnumRepaymentPeriod
{
	const description=array('1'=>'6期','2'=>'12期','4'=>'24期','8'=>'36期','16'=>'48期','32'=>'60期','64'=>'120期','128'=>'180期','256'=>'240期','512'=>'300期','1024'=>'360期');
		
	/**
     * 6期
	 * 6期
     */
    const p6 = 1;	
		
	/**
     * 12期
	 * 12期
     */
    const p12 = 2;	
		
	/**
     * 24期
	 * 24期
     */
    const p24 = 4;	
		
	/**
     * 36期
	 * 36期
     */
    const p36 = 8;	
		
	/**
     * 48期
	 * 48期
     */
    const p48 = 16;	
		
	/**
     * 60期
	 * 60期
     */
    const p60 = 32;	
		
	/**
     * 120期
	 * 120期
     */
    const p120 = 64;	
		
	/**
     * 180期
	 * 180期
     */
    const p180 = 128;	
		
	/**
     * 240期
	 * 240期（默认）
     */
    const p240 = 256;	
		
	/**
     * 300期
	 * 300期
     */
    const p300 = 512;	
		
	/**
     * 360期
	 * 360期
     */
    const p360 = 1024;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumRepaymentPeriod","fullName":"App\\Http\\Modules\\UMComponent\\GeneratedCodes\\Enum\\EnumRepaymentPeriod","displayName":"贷款期数","description":"贷款期数","items": [{"value":"1","name":"p6","displayName":"6期","description":"6期"},{"value":"2","name":"p12","displayName":"12期","description":"12期"},{"value":"4","name":"p24","displayName":"24期","description":"24期"},{"value":"8","name":"p36","displayName":"36期","description":"36期"},{"value":"16","name":"p48","displayName":"48期","description":"48期"},{"value":"32","name":"p60","displayName":"60期","description":"60期"},{"value":"64","name":"p120","displayName":"120期","description":"120期"},{"value":"128","name":"p180","displayName":"180期","description":"180期"},{"value":"256","name":"p240","displayName":"240期","description":"240期（默认）"},{"value":"512","name":"p300","displayName":"300期","description":"300期"},{"value":"1024","name":"p360","displayName":"360期","description":"360期"}]}';
	}
}
