<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-04-02 10:21:04
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 征信逾期
 * 征信逾期天数
 * 
 */
class EnumCreditOverdue
{
	const description=array('1'=>'无','2'=>'30天内','4'=>'30-60天','8'=>'60-90天','16'=>'90-120天','32'=>'120天以上');
		
	/**
     * 无
	 * 无逾期
     */
    const none = 1;	
		
	/**
     * 30天内
	 * 30天内
     */
    const d30 = 2;	
		
	/**
     * 30-60天
	 * 30-60天
     */
    const d30T60 = 4;	
		
	/**
     * 60-90天
	 * 60-90天
     */
    const d60T90 = 8;	
		
	/**
     * 90-120天
	 * 90-120天
     */
    const d90T120 = 16;	
		
	/**
     * 120天以上
	 * 120天以上
     */
    const d120P = 32;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumCreditOverdue","fullName":"App\\Http\\Modules\\UMComponent\\GeneratedCodes\\Enum\\EnumCreditOverdue","displayName":"征信逾期","description":"征信逾期天数","items": [{"value":"1","name":"none","displayName":"无","description":"无逾期"},{"value":"2","name":"d30","displayName":"30天内","description":"30天内"},{"value":"4","name":"d30T60","displayName":"30-60天","description":"30-60天"},{"value":"8","name":"d60T90","displayName":"60-90天","description":"60-90天"},{"value":"16","name":"d90T120","displayName":"90-120天","description":"90-120天"},{"value":"32","name":"d120P","displayName":"120天以上","description":"120天以上"}]}';
	}
}
