<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 产权类型
 * 产权类型
 * 
 */
class EnumPropertyRight
{
	const Description=array('1'=>'全款','2'=>'按揭','4'=>'抵押');
		
	/**
     * 全款
	 * 全款（默认）
     */
    const FullPayment = 1;	
		
	/**
     * 按揭
	 * 按揭
     */
    const Mortgage = 2;	
		
	/**
     * 抵押
	 * 抵押
     */
    const Guaranty = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
