<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 名下汽车
 * 名下汽车
 * 
 */
class EnumOwnerVehicleProperty
{
	const Description=array('1'=>'没有','2'=>'一辆','4'=>'二辆及以上');
		
	/**
     * 没有
	 * 没有
     */
    const None = 1;	
		
	/**
     * 一辆
	 * 一辆
     */
    const One = 2;	
		
	/**
     * 二辆及以上
	 * 二辆及以上
     */
    const TwoOrAbove = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
