<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 婚姻状况
 * 婚姻状况
 * 
 */
class EnumMarriageStatus
{
	const Description=array('1'=>'已婚','2'=>'未婚','4'=>'离异','8'=>'丧偶');
		
	/**
     * 已婚
	 * 已婚（默认）
     */
    const Married = 1;	
		
	/**
     * 未婚
	 * 未婚
     */
    const Single = 2;	
		
	/**
     * 离异
	 * 离异
     */
    const Divorced = 4;	
		
	/**
     * 丧偶
	 * 丧偶
     */
    const Widowed = 8;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
