<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM\enums;


/**
 * 投保险种
 * 投保险种
 * 
 */
class EnumInsuranceType
{
	const Description=array('1'=>'寿险','2'=>'教育险','4'=>'其他保险');
		
	/**
     * 寿险
	 * 寿险
     */
    const Life = 1;	
		
	/**
     * 教育险
	 * 教育险
     */
    const Education = 2;	
		
	/**
     * 其他保险
	 * 其他保险
     */
    const Others = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
