<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\uM;


/**
 * 缴费方式
 * 缴费方式
 * 
 */
class EnumInsurancePaymentType
{
	const Description=array('1'=>'按年','2'=>'按月','4'=>'按季','8'=>'趸交');
		
	/**
     * 按年
	 * 按年
     */
    const ByYear = 1;	
		
	/**
     * 按月
	 * 按月
     */
    const ByMonth = 2;	
		
	/**
     * 按季
	 * 按季
     */
    const BySeason = 4;	
		
	/**
     * 趸交
	 * 趸交
     */
    const Onetime = 8;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
