<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 建筑面积
 * 建筑面积
 * 
 */
class EnumMatchConstructionArea
{
	const Description=array('1'=>'60以下','2'=>'60~100','4'=>'100~200','8'=>'200以上');
		
	/**
     * 60以下
	 * 60以下
     */
    const Below60 = 1;	
		
	/**
     * 60~100
	 * 60~100
     */
    const Between60to100 = 2;	
		
	/**
     * 100~200
	 * 100~200
     */
    const Between100to200 = 4;	
		
	/**
     * 200以上
	 * 200以上
     */
    const Above200 = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
