<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 信用贷资质(可多选)
 * 信用贷资质(可多选)
 * 
 */
class EnumMatchCreaditQualification
{
	const Description=array('1'=>'银行打卡工资','2'=>'缴存2年3期以上商业保单','4'=>'本地连续缴纳6个月以上的社保、公积金');
		
	/**
     * 银行打卡工资
	 * 银行打卡工资
     */
    const SalaryOnCard = 1;	
		
	/**
     * 缴存2年3期以上商业保单
	 * 缴存2年3期以上商业保单
     */
    const Policy23 = 2;	
		
	/**
     * 本地连续缴纳6个月以上的社保、公积金
	 * 本地连续缴纳6个月以上的社保、公积金
     */
    const SocialSecurity6 = 4;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
