<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 缴纳期数
 * 保单缴纳期数（按月）
 * 
 */
class EnumMatchPolicePaymentPeriodByMonth
{
	const Description=array('1'=>'2期以下','2'=>'2~4期','4'=>'5~8期','8'=>'8期以上');
		
	/**
     * 2期以下
	 * 2期以下
     */
    const Below2 = 1;	
		
	/**
     * 2~4期
	 * 2~4期
     */
    const Between2to4 = 2;	
		
	/**
     * 5~8期
	 * 5~8期
     */
    const Between5to8 = 4;	
		
	/**
     * 8期以上
	 * 8期以上
     */
    const Above8 = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
