<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 社保缴存基数
 * 社保缴存基数
 * 
 */
class EnumMatchSocialSecurityBasic
{
	const Description=array('1'=>'按工资收入','2'=>'少于3千','4'=>'3~4千','8'=>'4~6千','16'=>'6~8千','32'=>'8千~1万','64'=>'1万~2万','128'=>'2万~3万','256'=>'3万以上');
		
	/**
     * 按工资收入
	 * 按工资收入
     */
    const BySalary = 1;	
		
	/**
     * 少于3千
	 * 少于3千
     */
    const Below3K = 2;	
		
	/**
     * 3~4千
	 * 3~4千
     */
    const Between3Kto4K = 4;	
		
	/**
     * 4~6千
	 * 4~6千
     */
    const Between4Kto6K = 8;	
		
	/**
     * 6~8千
	 * 6~8千
     */
    const Between6Kto8K = 16;	
		
	/**
     * 8千~1万
	 * 8千~1万
     */
    const Between8Kto1W = 32;	
		
	/**
     * 1万~2万
	 * 1万~2万
     */
    const Between1Wto2W = 64;	
		
	/**
     * 2万~3万
	 * 2万~3万
     */
    const Between2Wto3W = 128;	
		
	/**
     * 3万以上
	 * 3万以上
     */
    const Above3W = 256;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
