<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 车辆类型
 * 车辆类型
 * 
 */
class EnumMatchVehiclePropertyType
{
	const Description=array('1'=>'全款车','2'=>'按揭车');
		
	/**
     * 全款车
	 * 全款车
     */
    const Full = 1;	
		
	/**
     * 按揭车
	 * 按揭车
     */
    const Mortgage = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
