<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 建成时间
 * 建成时间
 * 
 */
class EnumMatchPropertyCompletionTime
{
	const Description=array('1'=>'10年以内','2'=>'10~20年','4'=>'20~30年','8'=>'30年以上');
		
	/**
     * 10年以内
	 * 10年以内
     */
    const Below10 = 1;	
		
	/**
     * 10~20年
	 * 10~20年
     */
    const Between10to20 = 2;	
		
	/**
     * 20~30年
	 * 20~30年
     */
    const Between20to30 = 4;	
		
	/**
     * 30年以上
	 * 30年以上
     */
    const Above30 = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
