<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 公积金缴存情况
 * 公积金缴存情况
 * 
 */
class EnumMatchProvidentFundStatus
{
	const Description=array('1'=>'无公积金','2'=>'持续缴纳中');
		
	/**
     * 无公积金
	 * 无公积金
     */
    const None = 1;	
		
	/**
     * 持续缴纳中
	 * 持续缴纳中
     */
    const Continuous = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
