<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 每月银行卡打卡工资
 * 每月银行卡打卡工资
 * 
 */
class EnumMatchSalary
{
	const Description=array('1'=>'少于3千','2'=>'3~4千','4'=>'4~6千','8'=>'6~8千','16'=>'8千~1万','32'=>'1万~2万','64'=>'2万~3万','128'=>'3万以上');
		
	/**
     * 少于3千
	 * 少于3千
     */
    const Below3K = 1;	
		
	/**
     * 3~4千
	 * 3~4千
     */
    const Between3Kto4K = 2;	
		
	/**
     * 4~6千
	 * 4~6千
     */
    const Between4Kto6K = 4;	
		
	/**
     * 6~8千
	 * 6~8千
     */
    const Between6Kto8K = 8;	
		
	/**
     * 8千~1万
	 * 8千~1万
     */
    const Between8Kto1W = 16;	
		
	/**
     * 1万~2万
	 * 1万~2万
     */
    const Between1Wto2W = 32;	
		
	/**
     * 2万~3万
	 * 2万~3万
     */
    const Between2Wto3W = 64;	
		
	/**
     * 3万以上
	 * 3万以上
     */
    const Above3W = 128;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
