<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-19 16:10:43
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 社保缴存情况
 * 社保缴存情况
 * 
 */
class EnumMatchSocialSecurityStatus
{
	const description=array('1'=>'无社保','2'=>'持续缴纳中');
		
	/**
     * 无社保
	 * 无社保
     */
    const none = 1;	
		
	/**
     * 持续缴纳中
	 * 持续缴纳中
     */
    const continuous = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMatchSocialSecurityStatus","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumMatchSocialSecurityStatus","displayName":"社保缴存情况","description":"社保缴存情况","items": [{"value":"1","name":"none","displayName":"无社保","description":"无社保"},{"value":"2","name":"continuous","displayName":"持续缴纳中","description":"持续缴纳中"}]}';
	}
}
