<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-22 16:41:31
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 贷款期数
 * 贷款期数（按揭房）
 * 
 */
class EnumMatchHouseRepaymentPeriod
{
	const description=array('1'=>'1~3期','2'=>'4~6期','4'=>'7~12期','8'=>'13~24期','16'=>'25~36期','32'=>'37~60期','64'=>'60期以上');
		
	/**
     * 1~3期
	 * 1~3期
     */
    const between1to3 = 1;	
		
	/**
     * 4~6期
	 * 4~6期
     */
    const between4to6 = 2;	
		
	/**
     * 7~12期
	 * 7~12期
     */
    const between7to12 = 4;	
		
	/**
     * 13~24期
	 * 13~24期
     */
    const between13to24 = 8;	
		
	/**
     * 25~36期
	 * 25~36期
     */
    const between25to36 = 16;	
		
	/**
     * 37~60期
	 * 37~60期
     */
    const between37to60 = 32;	
		
	/**
     * 60期以上
	 * 60期以上
     */
    const above60 = 64;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMatchHouseRepaymentPeriod","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumMatchHouseRepaymentPeriod","displayName":"贷款期数","description":"贷款期数（按揭房）","items": [{"value":"1","name":"between1to3","displayName":"1~3期","description":"1~3期"},{"value":"2","name":"between4to6","displayName":"4~6期","description":"4~6期"},{"value":"4","name":"between7to12","displayName":"7~12期","description":"7~12期"},{"value":"8","name":"between13to24","displayName":"13~24期","description":"13~24期"},{"value":"16","name":"between25to36","displayName":"25~36期","description":"25~36期"},{"value":"32","name":"between37to60","displayName":"37~60期","description":"37~60期"},{"value":"64","name":"above60","displayName":"60期以上","description":"60期以上"}]}';
	}
}
