<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-04-02 10:21:03
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 取消报单原因
 * 取消报单原因
 * 
 */
class EnumApplicationCancelReason
{
	const description=array('1'=>'客户已筹措到资金','2'=>'客户资料需要修改','4'=>'需重新与客户沟通');
		
	/**
     * 客户已筹措到资金
	 * 客户已筹措到资金
     */
    const alreadyHaveFunds = 1;	
		
	/**
     * 客户资料需要修改
	 * 客户资料需要修改
     */
    const dataChange = 2;	
		
	/**
     * 需重新与客户沟通
	 * 需重新与客户沟通
     */
    const reconnect = 4;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumApplicationCancelReason","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumApplicationCancelReason","displayName":"取消报单原因","description":"取消报单原因","items": [{"value":"1","name":"alreadyHaveFunds","displayName":"客户已筹措到资金","description":"客户已筹措到资金"},{"value":"2","name":"dataChange","displayName":"客户资料需要修改","description":"客户资料需要修改"},{"value":"4","name":"reconnect","displayName":"需重新与客户沟通","description":"需重新与客户沟通"}]}';
	}
}
