<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 缴纳方式
 * 保单缴纳方式
 * 
 */
class EnumMatchPolicePaymentType
{
	const Description=array('1'=>'年','2'=>'月','4'=>'季');
		
	/**
     * 年
	 * 年
     */
    const ByYear = 1;	
		
	/**
     * 月
	 * 月
     */
    const ByMonth = 2;	
		
	/**
     * 季
	 * 季
     */
    const BySeason = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
