<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 缴纳期数
 * 保单缴纳期数（按年）
 * 
 */
class EnumMatchPolicePaymentPeriodByYear
{
	const Description=array('1'=>'不足2年3期','2'=>'2年3期','4'=>'3年4期','8'=>'4年5期','16'=>'6年6期','32'=>'6年7期以上');
		
	/**
     * 不足2年3期
	 * 不足2年3期
     */
    const Below2Y3P = 1;	
		
	/**
     * 2年3期
	 * 2年3期
     */
    const TwoY3P = 2;	
		
	/**
     * 3年4期
	 * 3年4期
     */
    const ThreeY4P = 4;	
		
	/**
     * 4年5期
	 * 4年5期
     */
    const FourY5P = 8;	
		
	/**
     * 6年6期
	 * 6年6期
     */
    const FiveY6P = 16;	
		
	/**
     * 6年7期以上
	 * 6年7期以上
     */
    const Above6Y7P = 32;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
