<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 取消报单原因
 * 取消报单原因
 * 
 */
class EnumApplicationCancelReason
{
	const Description=array('1'=>'客户已筹措到资金','2'=>'客户资料需要修改','4'=>'需重新与客户沟通');
		
	/**
     * 客户已筹措到资金
	 * 客户已筹措到资金
     */
    const AlreadyHaveFunds = 1;	
		
	/**
     * 客户资料需要修改
	 * 客户资料需要修改
     */
    const DataChange = 2;	
		
	/**
     * 需重新与客户沟通
	 * 需重新与客户沟通
     */
    const Reconnect = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
