<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-07-04 10:55:11
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 车辆类型
 * 车辆类型
 * 
 */
class EnumMatchVehiclePropertyType
{
	const description=array('1'=>'全款车','2'=>'按揭车');
		
	/**
     * 全款车
	 * 全款车
     */
    const full = 1;	
		
	/**
     * 按揭车
	 * 按揭车
     */
    const mortgage = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMatchVehiclePropertyType","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumMatchVehiclePropertyType","displayName":"车辆类型","description":"车辆类型","items": [{"value":"1","name":"full","displayName":"全款车","description":"全款车"},{"value":"2","name":"mortgage","displayName":"按揭车","description":"按揭车"}]}';
	}
}
