<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 户籍
 * 户籍
 * 
 */
class EnumCensus
{
	const Description=array('1'=>'本地','2'=>'外地');
		
	/**
     * 本地
	 * 本地
     */
    const Local = 1;	
		
	/**
     * 外地
	 * 外地
     */
    const Field = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
