<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-06-06 13:57:50
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 签单申请超期关闭原因
 * 签单申请超期关闭原因
 * 
 */
class EnumApplicationTimeoutReason
{
	const description=array('1'=>'等待签单时间超期','2'=>'方案转协议超期');
		
	/**
     * 等待签单时间超期
	 * 等待签单时间超期
     */
    const timeoutBySign = 1;	
		
	/**
     * 方案转协议超期
	 * 方案转协议超期
     */
    const timeoutbyAgreement = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumApplicationTimeoutReason","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumApplicationTimeoutReason","displayName":"签单申请超期关闭原因","description":"签单申请超期关闭原因","items": [{"value":"1","name":"timeoutBySign","displayName":"等待签单时间超期","description":"等待签单时间超期"},{"value":"2","name":"timeoutbyAgreement","displayName":"方案转协议超期","description":"方案转协议超期"}]}';
	}
}
