<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 连续缴存期数
 * 连续缴存期数
 * 
 */
class EnumMatchProvidentFundPeriod
{
	const Description=array('1'=>'6个月~1年','2'=>'1~2年','4'=>'2~3年','8'=>'3年以上');
		
	/**
     * 6个月~1年
	 * 6个月~1年
     */
    const Between6Mto1Y = 1;	
		
	/**
     * 1~2年
	 * 1~2年
     */
    const Between1Yto2Y = 2;	
		
	/**
     * 2~3年
	 * 2~3年
     */
    const Between2Yto3Y = 4;	
		
	/**
     * 3年以上
	 * 3年以上
     */
    const Above3Y = 8;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
