<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 社保缴存情况
 * 社保缴存情况
 * 
 */
class EnumMatchSocialSecurityStatus
{
	const Description=array('1'=>'无社保','2'=>'持续缴纳中');
		
	/**
     * 无社保
	 * 无社保
     */
    const None = 1;	
		
	/**
     * 持续缴纳中
	 * 持续缴纳中
     */
    const Continuous = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
