<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 车辆上户情况
 * 车辆上户情况
 * 
 */
class EnumMatchVehicleRegistraionTime
{
	const Description=array('1'=>'不足3个月','2'=>'超过三个月');
		
	/**
     * 不足3个月
	 * 不足3个月
     */
    const Below3M = 1;	
		
	/**
     * 超过三个月
	 * 超过三个月
     */
    const Above3M = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
