<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 打卡工资期数
 * 打卡工资期数
 * 
 */
class EnumMatchSalaryPeriod
{
	const Description=array('0'=>'无','1'=>'1~3个月','2'=>'4~6个月','4'=>'7~12个月','8'=>'13~24个月','16'=>'25~36个月','32'=>'36个月以上');
		
	/**
     * 无
	 * 无
     */
    const None = 0;	
		
	/**
     * 1~3个月
	 * 1~3个月
     */
    const Oneto3 = 1;	
		
	/**
     * 4~6个月
	 * 4~6个月
     */
    const Fourto6 = 2;	
		
	/**
     * 7~12个月
	 * 7~12个月
     */
    const Sevento12 = 4;	
		
	/**
     * 13~24个月
	 * 13~24个月
     */
    const Thirteento24 = 8;	
		
	/**
     * 25~36个月
	 * 25~36个月
     */
    const Tweentyfiveto36 = 16;	
		
	/**
     * 36个月以上
	 * 36个月以上
     */
    const Above36 = 32;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
