<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-09-12 14:15:23
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 信用贷资质(可多选)
 * 信用贷资质(可多选)
 * 
 */
class EnumMatchCreaditQualification
{
	const description=array('0'=>'未定义','1'=>'银行打卡工资','2'=>'缴存2年3期以上商业保单','4'=>'本地连续缴纳6个月以上的社保、公积金');
		
	/**
     * 银行打卡工资
	 * 银行打卡工资
     */
    const salaryOnCard = 1;	
		
	/**
     * 缴存2年3期以上商业保单
	 * 缴存2年3期以上商业保单
     */
    const policy23 = 2;	
		
	/**
     * 本地连续缴纳6个月以上的社保、公积金
	 * 本地连续缴纳6个月以上的社保、公积金
     */
    const socialSecurity6 = 4;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMatchCreaditQualification","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumMatchCreaditQualification","displayName":"信用贷资质(可多选)","description":"信用贷资质(可多选)","items": [{"value":"1","name":"salaryOnCard","displayName":"银行打卡工资","description":"银行打卡工资"},{"value":"2","name":"policy23","displayName":"缴存2年3期以上商业保单","description":"缴存2年3期以上商业保单"},{"value":"4","name":"socialSecurity6","displayName":"本地连续缴纳6个月以上的社保、公积金","description":"本地连续缴纳6个月以上的社保、公积金"}]}';
	}
}
