<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 还款期数
 * 还款期数（按揭房）
 * 
 */
class EnumMatchHouseRepaymentPeriod
{
	const Description=array('1'=>'1~3期','2'=>'4~6期','4'=>'7~12期','8'=>'13~24期','16'=>'25~36期','32'=>'37~60期','64'=>'60期以上');
		
	/**
     * 1~3期
	 * 1~3期
     */
    const Between1to3 = 1;	
		
	/**
     * 4~6期
	 * 4~6期
     */
    const Between4to6 = 2;	
		
	/**
     * 7~12期
	 * 7~12期
     */
    const Between7to12 = 4;	
		
	/**
     * 13~24期
	 * 13~24期
     */
    const Between13to24 = 8;	
		
	/**
     * 25~36期
	 * 25~36期
     */
    const Between25to36 = 16;	
		
	/**
     * 37~60期
	 * 37~60期
     */
    const Between37to60 = 32;	
		
	/**
     * 60期以上
	 * 60期以上
     */
    const Above60 = 64;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
