<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 房产类型
 * 房产类型
 * 
 */
class EnumMatchHousePropertyType
{
	const Description=array('1'=>'全款房','2'=>'按揭房');
		
	/**
     * 全款房
	 * 全款房
     */
    const FullHouse = 1;	
		
	/**
     * 按揭房
	 * 按揭房
     */
    const MortgageHouse = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
