<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-07-04 10:55:11
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 缴纳期数
 * 保单缴纳期数（按季）
 * 
 */
class EnumMatchPolicePaymentPeriodBySeason
{
	const description=array('1'=>'6期以下','2'=>'6~12期','4'=>'13~24期','8'=>'24期以上');
		
	/**
     * 6期以下
	 * 6期以下
     */
    const below6 = 1;	
		
	/**
     * 6~12期
	 * 6~12期
     */
    const between6to12 = 2;	
		
	/**
     * 13~24期
	 * 13~24期
     */
    const between13to24 = 4;	
		
	/**
     * 24期以上
	 * 24期以上
     */
    const above24 = 8;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMatchPolicePaymentPeriodBySeason","fullName":"App\\Http\\Modules\\MatchComponent\\GeneratedCodes\\Enum\\EnumMatchPolicePaymentPeriodBySeason","displayName":"缴纳期数","description":"保单缴纳期数（按季）","items": [{"value":"1","name":"below6","displayName":"6期以下","description":"6期以下"},{"value":"2","name":"between6to12","displayName":"6~12期","description":"6~12期"},{"value":"4","name":"between13to24","displayName":"13~24期","description":"13~24期"},{"value":"8","name":"above24","displayName":"24期以上","description":"24期以上"}]}';
	}
}
