<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match;


/**
 * 征信情况
 * 征信情况
 * 
 */
class EnumMatchCreditInformation
{
	const Description=array('1'=>'无信用卡或贷款','2'=>'信用良好','4'=>'1年多次逾期');
		
	/**
     * 无信用卡或贷款
	 * 无信用卡或贷款
     */
    const NoCreditCardAndLoan = 1;	
		
	/**
     * 信用良好
	 * 信用良好
     */
    const GoodCredit = 2;	
		
	/**
     * 1年多次逾期
	 * 1年多次逾期
     */
    const BadCredit = 4;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
