<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 选择贷款类型（可多选）
 * 选择贷款类型（可多选）
 * 
 */
class EnumMatchLoanType
{
	const Description=array('1'=>'房产抵押','2'=>'车辆贷款','4'=>'信用贷款');
		
	/**
     * 房产抵押
	 * 房产抵押
     */
    const Mortgage = 1;	
		
	/**
     * 车辆贷款
	 * 车辆贷款
     */
    const VehicleMortage = 2;	
		
	/**
     * 信用贷款
	 * 信用贷款
     */
    const CreditLoans = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
