<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 签单申请关闭类型
 * 签单申请关闭类型
 * 
 */
class EnumApplicationCloseType
{
	const Description=array('0'=>'未关闭','1'=>'已签单','2'=>'超期关闭','4'=>'无效关闭','8'=>'取消报单','16'=>'重复报单');
		
	/**
     * 未关闭
	 * 未关闭
     */
    const None = 0;	
		
	/**
     * 已签单
	 * 已签单
     */
    const Signed = 1;	
		
	/**
     * 超期关闭
	 * 超期关闭
     */
    const Timeout = 2;	
		
	/**
     * 无效关闭
	 * 无效关闭
     */
    const Invalid = 4;	
		
	/**
     * 取消报单
	 * 取消报单
     */
    const Cancel = 8;	
		
	/**
     * 重复报单
	 * 重复报单
     */
    const Repeat = 16;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
