<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 行驶里程数（万公里）
 * 行驶里程数（万公里）
 * 
 */
class EnumMatchVehicleMileage
{
	const Description=array('1'=>'12万以内','2'=>'12万以上');
		
	/**
     * 12万以内
	 * 12万以内
     */
    const Below12 = 1;	
		
	/**
     * 12万以上
	 * 12万以上
     */
    const Above12 = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
