<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\match\enums;


/**
 * 签单申请超期关闭原因
 * 签单申请超期关闭原因
 * 
 */
class EnumApplicationTimeoutReason
{
	const Description=array('1'=>'等待签单时间超期','2'=>'方案转协议超期');
		
	/**
     * 等待签单时间超期
	 * 等待签单时间超期
     */
    const TimeoutBySign = 1;	
		
	/**
     * 方案转协议超期
	 * 方案转协议超期
     */
    const TimeoutbyAgreement = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
