<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\mD\enums;


/**
 * UI元数据类型
 * UI元数据类型
 * 
 */
class EnumUIMDElementType
{
	const Description=array('1'=>'页面','2'=>'菜单','4'=>'按钮');
		
	/**
     * 页面
	 * 页面
     */
    const Page = 1;	
		
	/**
     * 菜单
	 * 菜单
     */
    const Menu = 2;	
		
	/**
     * 按钮
	 * 按钮
     */
    const Button = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
