<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-07-04 10:55:11
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\mD\enums;


/**
 * UI元数据类型
 * UI元数据类型
 * 
 */
class EnumUIMDElementType
{
	const description=array('1'=>'页面','2'=>'菜单','4'=>'按钮');
		
	/**
     * 页面
	 * 页面
     */
    const page = 1;	
		
	/**
     * 菜单
	 * 菜单
     */
    const menu = 2;	
		
	/**
     * 按钮
	 * 按钮
     */
    const button = 4;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumUIMDElementType","fullName":"App\\Http\\Modules\\MDComponent\\GeneratedCodes\\Enum\\EnumUIMDElementType","displayName":"UI元数据类型","description":"UI元数据类型","items": [{"value":"1","name":"page","displayName":"页面","description":"页面"},{"value":"2","name":"menu","displayName":"菜单","description":"菜单"},{"value":"4","name":"button","displayName":"按钮","description":"按钮"}]}';
	}
}
