<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:38
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement;


/**
 * 协议取消签单原因
 * 协议取消签单原因
 * 
 */
class EnumAgreementCancelReason
{
	const Description=array('1'=>'客户改变决定，放弃签单','2'=>'客户已筹措到资金');
		
	/**
     * 客户改变决定，放弃签单
	 * 客户改变决定，放弃签单
     */
    const ChangeMind = 1;	
		
	/**
     * 客户已筹措到资金
	 * 客户已筹措到资金
     */
    const AlreadyHaveFunds = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key]) ? self::Description[$key] : '';
    }
}
