<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-09-12 14:15:23
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 订单类型
 * 订单类型
 * 
 */
class EnumOrderType
{
	const description=array('0'=>'未定义','3'=>'房产贷款','4'=>'车辆贷款','8'=>'消费信贷','16'=>'小额信贷','32'=>'企业信贷');
		
	/**
     * 房产贷款
	 * 房产贷款
     */
    const houseMortgage = 3;	
		
	/**
     * 车辆贷款
	 * 车辆贷款
     */
    const vehicleMortgage = 4;	
		
	/**
     * 消费信贷
	 * 消费金融信贷
     */
    const consumerCredit = 8;	
		
	/**
     * 小额信贷
	 * 小额信用贷款
     */
    const microfinance = 16;	
		
	/**
     * 企业信贷
	 * 企业经营信贷
     */
    const corporateCredit = 32;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumOrderType","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumOrderType","displayName":"订单类型","description":"订单类型","items": [{"value":"3","name":"houseMortgage","displayName":"房产贷款","description":"房产贷款"},{"value":"4","name":"vehicleMortgage","displayName":"车辆贷款","description":"车辆贷款"},{"value":"8","name":"consumerCredit","displayName":"消费信贷","description":"消费金融信贷"},{"value":"16","name":"microfinance","displayName":"小额信贷","description":"小额信用贷款"},{"value":"32","name":"corporateCredit","displayName":"企业信贷","description":"企业经营信贷"}]}';
	}
}
