<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 产品服务费收取类型
 * 产品服务费收取类型
 * 
 */
class EnumFeeType
{
	const Description=array('1'=>'一口价','2'=>'按比例');
		
	/**
     * 一口价
	 * 一口价
     */
    const Price = 1;	
		
	/**
     * 按比例
	 * 按比例
     */
    const Prorated = 2;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
