<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-01 11:29:41
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 协议业务
 * 协议业务
 * 
 */
class EnumAgreementBusinessState
{
	const description=array('1'=>'初始','2'=>'等待','4'=>'操作中','8'=>'关闭');
		
	/**
     * 初始
	 * 初始（或草稿）状态
     */
    const initial = 1;	
		
	/**
     * 等待
	 * 等待中状态
     */
    const waiting = 2;	
		
	/**
     * 操作中
	 * 操作中状态
     */
    const running = 4;	
		
	/**
     * 关闭
	 * 已关闭
     */
    const closed = 8;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumAgreementBusinessState","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumAgreementBusinessState","displayName":"协议业务","description":"协议业务","items": [{"value":"1","name":"initial","displayName":"初始","description":"初始（或草稿）状态"},{"value":"2","name":"waiting","displayName":"等待","description":"等待中状态"},{"value":"4","name":"running","displayName":"操作中","description":"操作中状态"},{"value":"8","name":"closed","displayName":"关闭","description":"已关闭"}]}';
	}
}
