<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:38
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement;


/**
 * 订单业务状态
 * 订单业务状态
 * 
 */
class EnumOrderBusinessState
{
	const Description=array('1'=>'初始','2'=>'等待','4'=>'操作中','8'=>'关闭');
		
	/**
     * 初始
	 * 初始状态
     */
    const Initial = 1;	
		
	/**
     * 等待
	 * 等待中状态
     */
    const Waiting = 2;	
		
	/**
     * 操作中
	 * 操作中状态
     */
    const Running = 4;	
		
	/**
     * 关闭
	 * 已关闭
     */
    const Closed = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key]) ? self::Description[$key] : '';
    }
}
