<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-01 11:29:41
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 订单系统关闭原因
 * 订单系统关闭原因
 * 
 */
class EnumOrderSystemCloseReason
{
	const description=array('1'=>'任一订单完成进件后，其余订单超时关闭','2'=>'任一订单完成放款后，其余订单超时关闭','4'=>'订单完成后，无活跃订单，超时关闭');
		
	/**
     * 任一订单完成进件后，其余订单超时关闭
	 * 任一订单完成进件后，其余订单超时关闭
     */
    const timeoutAfterOneComplete = 1;	
		
	/**
     * 任一订单完成放款后，其余订单超时关闭
	 * 任一订单完成放款后，其余订单超时关闭
     */
    const timeoutAfterOneLoaned = 2;	
		
	/**
     * 订单完成后，无活跃订单，超时关闭
	 * 订单完成后，无活跃订单，超时关闭
     */
    const timeoutAferAllComplete = 4;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumOrderSystemCloseReason","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumOrderSystemCloseReason","displayName":"订单系统关闭原因","description":"订单系统关闭原因","items": [{"value":"1","name":"timeoutAfterOneComplete","displayName":"任一订单完成进件后，其余订单超时关闭","description":"任一订单完成进件后，其余订单超时关闭"},{"value":"2","name":"timeoutAfterOneLoaned","displayName":"任一订单完成放款后，其余订单超时关闭","description":"任一订单完成放款后，其余订单超时关闭"},{"value":"4","name":"timeoutAferAllComplete","displayName":"订单完成后，无活跃订单，超时关闭","description":"订单完成后，无活跃订单，超时关闭"}]}';
	}
}
