<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-04 10:22:57
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 协议系统关闭原因
 * 协议系统关闭原因
 * 
 */
class EnumAgreementSystemCloseReason
{
	const description=array('1'=>'签单后未提交订单超时，且超期未分配订单','2'=>'订单无效后超时','4'=>'订单完成后超时');
		
	/**
     * 签单后未提交订单超时，且超期未分配订单
	 * 签单后未提交订单超时，且超期未分配订单
     */
    const timeOutAfterSigned = 1;	
		
	/**
     * 订单无效后超时
	 * 订单无效后超时
     */
    const timeoutAfterInvalid = 2;	
		
	/**
     * 订单完成后超时
	 * 订单完成后超时
     */
    const timeoutAfterComplete = 4;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumAgreementSystemCloseReason","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumAgreementSystemCloseReason","displayName":"协议系统关闭原因","description":"协议系统关闭原因","items": [{"value":"1","name":"timeOutAfterSigned","displayName":"签单后未提交订单超时，且超期未分配订单","description":"签单后未提交订单超时，且超期未分配订单"},{"value":"2","name":"timeoutAfterInvalid","displayName":"订单无效后超时","description":"订单无效后超时"},{"value":"4","name":"timeoutAfterComplete","displayName":"订单完成后超时","description":"订单完成后超时"}]}';
	}
}
