<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:38
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement;


/**
 * 子订单客户结算关闭原因
 * 子订单客户结算关闭原因
 * 
 */
class EnumProjectSettlementCloseType
{
	const Description=array('0'=>'未关闭','1'=>'结案完成','2'=>'呆账坏账','4'=>'系统关闭');
		
	/**
     * 未关闭
	 * 未关闭（初始）
     */
    const None = 0;	
		
	/**
     * 结案完成
	 * 结案完成
     */
    const Complete = 1;	
		
	/**
     * 呆账坏账
	 * 呆账坏账
     */
    const BadDebt = 2;	
		
	/**
     * 系统关闭
	 * 0
     */
    const SystemClose = 4;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
