<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-19 16:10:41
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 子订单失败关闭原因
 * 子订单失败关闭原因
 * 
 */
class EnumProjectFailureReason
{
	const description=array('1'=>'此渠道暂时无法提供资金','2'=>'渠道人员提交资料被打回');
		
	/**
     * 此渠道暂时无法提供资金
	 * 此渠道暂时无法提供资金
     */
    const unableToLoan = 1;	
		
	/**
     * 渠道人员提交资料被打回
	 * 渠道人员提交资料被打回
     */
    const infoReturned = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumProjectFailureReason","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumProjectFailureReason","displayName":"子订单失败关闭原因","description":"子订单失败关闭原因","items": [{"value":"1","name":"unableToLoan","displayName":"此渠道暂时无法提供资金","description":"此渠道暂时无法提供资金"},{"value":"2","name":"infoReturned","displayName":"渠道人员提交资料被打回","description":"渠道人员提交资料被打回"}]}';
	}
}
