<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-01 11:29:41
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 子订单系统关闭原因
 * 子订单系统关闭原因
 * 
 */
class EnumProjectSystemCloseReason
{
	const description=array('1'=>'因订单无效拒单关闭','2'=>'因订单取消签单关闭','4'=>'因订单超时关闭','8'=>'因同一订单中，子订单放款，且已超时，其余子订单超时关闭','16'=>'因同一订单中，子订单完成进件，且已超时，其余子订单超时关闭','32'=>'因其他订单完成放款，其余订单关闭而关闭','64'=>'因其他订单完成进件，其余订单关闭而关闭');
		
	/**
     * 因订单无效拒单关闭
	 * 因订单无效拒单关闭
     */
    const orderInvalid = 1;	
		
	/**
     * 因订单取消签单关闭
	 * 因订单取消签单关闭
     */
    const orderCancel = 2;	
		
	/**
     * 因订单超时关闭
	 * 因订单超时关闭
     */
    const orderTimeout = 4;	
		
	/**
     * 因同一订单中，子订单放款，且已超时，其余子订单超时关闭
	 * 因同一订单中，子订单放款，且已超时，其余子订单超时关闭
     */
    const moreReason1 = 8;	
		
	/**
     * 因同一订单中，子订单完成进件，且已超时，其余子订单超时关闭
	 * 因同一订单中，子订单完成进件，且已超时，其余子订单超时关闭
     */
    const moreReason2 = 16;	
		
	/**
     * 因其他订单完成放款，其余订单关闭而关闭
	 * 因其他订单完成放款，其余订单关闭而关闭
     */
    const moreReason3 = 32;	
		
	/**
     * 因其他订单完成进件，其余订单关闭而关闭
	 * 因其他订单完成进件，其余订单关闭而关闭
     */
    const moreReason4 = 64;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumProjectSystemCloseReason","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumProjectSystemCloseReason","displayName":"子订单系统关闭原因","description":"子订单系统关闭原因","items": [{"value":"1","name":"orderInvalid","displayName":"因订单无效拒单关闭","description":"因订单无效拒单关闭"},{"value":"2","name":"orderCancel","displayName":"因订单取消签单关闭","description":"因订单取消签单关闭"},{"value":"4","name":"orderTimeout","displayName":"因订单超时关闭","description":"因订单超时关闭"},{"value":"8","name":"moreReason1","displayName":"因同一订单中，子订单放款，且已超时，其余子订单超时关闭","description":"因同一订单中，子订单放款，且已超时，其余子订单超时关闭"},{"value":"16","name":"moreReason2","displayName":"因同一订单中，子订单完成进件，且已超时，其余子订单超时关闭","description":"因同一订单中，子订单完成进件，且已超时，其余子订单超时关闭"},{"value":"32","name":"moreReason3","displayName":"因其他订单完成放款，其余订单关闭而关闭","description":"因其他订单完成放款，其余订单关闭而关闭"},{"value":"64","name":"moreReason4","displayName":"因其他订单完成进件，其余订单关闭而关闭","description":"因其他订单完成进件，其余订单关闭而关闭"}]}';
	}
}
