<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:38
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement;


/**
 * 子订单关闭类型
 * 子订单关闭类型
 * 
 */
class EnumProjectCloseType
{
	const Description=array('0'=>'未关闭','1'=>'渠道放款','2'=>'失败关闭','4'=>'客户退单','8'=>'系统关闭','16'=>'历史数据');
		
	/**
     * 未关闭
	 * 未关闭
     */
    const None = 0;	
		
	/**
     * 渠道放款
	 * 渠道放款
     */
    const GetLoan = 1;	
		
	/**
     * 失败关闭
	 * 失败关闭
     */
    const Failure = 2;	
		
	/**
     * 客户退单
	 * 客户退单
     */
    const Chargeback = 4;	
		
	/**
     * 系统关闭
	 * 系统关闭
     */
    const System = 8;	
		
	/**
     * 历史数据
	 * 历史数据
     */
    const History = 16;	
      
	public static function getDescription($key){
        return isset(self::Description[$key]) ? self::Description[$key] : '';
    }
}
