<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:38
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement;


/**
 * 线上协议归档状态
 * 线上协议归档状态
 * 
 */
class EnumOnlineAgreementFileState
{
	const Description=array('1'=>'申请','2'=>'归档','4'=>'变更');
		
	/**
     * 申请
	 * 线上协议申请状态
     */
    const Apply = 1;	
		
	/**
     * 归档
	 * 线上协议归档状态
     */
    const Filed = 2;	
		
	/**
     * 变更
	 * 线上协议无效状态
     */
    const Changed = 4;	
      
	public static function getDescription($key){
        return isset(self::Description[$key]) ? self::Description[$key] : '';
    }
}
