<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 拒单原因
 * 拒单原因
 * 
 */
class EnumLoanReasonForRejection
{
	const Description=array('1'=>'大数据核查不通过','2'=>'失信，有诉讼执行','4'=>'经营考察不过','8'=>'评分不足','16'=>'禁入行业','32'=>'征信不良','64'=>'抵押物太差','128'=>'负债过高','256'=>'流水违禁','512'=>'面谈违禁','1024'=>'电话异常（信息虚假）');
		
	/**
     * 大数据核查不通过
	 * 大数据核查不通过
     */
    const DataVerificationFails = 1;	
		
	/**
     * 失信，有诉讼执行
	 * 失信，有诉讼执行
     */
    const LitigationExecution = 2;	
		
	/**
     * 经营考察不过
	 * 经营考察不过
     */
    const BusinessInvestigateFails = 4;	
		
	/**
     * 评分不足
	 * 评分不足
     */
    const Underestimation = 8;	
		
	/**
     * 禁入行业
	 * 禁入行业
     */
    const ForbiddenIndustry = 16;	
		
	/**
     * 征信不良
	 * 征信不良
     */
    const BadCredit = 32;	
		
	/**
     * 抵押物太差
	 * 抵押物太差
     */
    const BadCollateral = 64;	
		
	/**
     * 负债过高
	 * 负债过高
     */
    const HighDebt = 128;	
		
	/**
     * 流水违禁
	 * 流水违禁
     */
    const IllegalFundFlow = 256;	
		
	/**
     * 面谈违禁
	 * 面谈违禁
     */
    const IllegalInterview = 512;	
		
	/**
     * 电话异常（信息虚假）
	 * 电话异常（信息虚假）
     */
    const FalseInformatio = 1024;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
