<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 贷款类型
 * 贷款类型
 * 
 */
class EnumLoanType
{
	const Description=array('1'=>'全款房贷','2'=>'房产二抵','4'=>'车辆贷款','8'=>'消费信贷','16'=>'小额信贷','32'=>'企业信贷','64'=>'新一贷');
		
	/**
     * 全款房贷
	 * 全款房抵押贷款
     */
    const FullMortgage = 1;	
		
	/**
     * 房产二抵
	 * 房产再次抵押贷款
     */
    const SecondaryMoetgage = 2;	
		
	/**
     * 车辆贷款
	 * 车辆贷款
     */
    const VehicleMortgage = 4;	
		
	/**
     * 消费信贷
	 * 消费金融信贷
     */
    const ConsumerCredit = 8;	
		
	/**
     * 小额信贷
	 * 小额信用贷款
     */
    const Microfinance = 16;	
		
	/**
     * 企业信贷
	 * 企业经营信贷
     */
    const CorporateCredit = 32;	
		
	/**
     * 新一贷
	 * 新一贷
     */
    const XinYiDai = 64;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
