<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-07-16 15:13:42
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 子订单客户结算状态
 * 子订单客户结算状态
 * 
 */
class EnumProjectSettlementState
{
	const description=array('1'=>'初始','2'=>'等待中','4'=>'结算中','8'=>'已关闭');
		
	/**
     * 初始
	 * 初始
     */
    const inital = 1;	
		
	/**
     * 等待中
	 * 等待中
     */
    const waiting = 2;	
		
	/**
     * 结算中
	 * 结算中
     */
    const running = 4;	
		
	/**
     * 已关闭
	 * 已关闭
     */
    const closed = 8;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumProjectSettlementState","fullName":"App\\Http\\Modules\\AgreementComponent\\GeneratedCodes\\Enum\\EnumProjectSettlementState","displayName":"子订单客户结算状态","description":"子订单客户结算状态","items": [{"value":"1","name":"inital","displayName":"初始","description":"初始"},{"value":"2","name":"waiting","displayName":"等待中","description":"等待中"},{"value":"4","name":"running","displayName":"结算中","description":"结算中"},{"value":"8","name":"closed","displayName":"已关闭","description":"已关闭"}]}';
	}
}
