<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:21
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\agreement\enums;


/**
 * 订单关闭类型
 * 订单关闭类型
 * 
 */
class EnumOrderCloseType
{
	const Description=array('0'=>'未关闭','1'=>'业务完成','2'=>'无效拒单','4'=>'取消签单','8'=>'系统关闭');
		
	/**
     * 未关闭
	 * 未关闭
     */
    const None = 0;	
		
	/**
     * 业务完成
	 * 业务完成
     */
    const Complete = 1;	
		
	/**
     * 无效拒单
	 * 无效拒单
     */
    const Invalid = 2;	
		
	/**
     * 取消签单
	 * 取消签单
     */
    const Cancel = 4;	
		
	/**
     * 系统关闭
	 * 系统关闭
     */
    const System = 8;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
