<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-09-12 14:15:23
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message\enums;


/**
 * 消息类型
 * 消息的类型
 * 
 */
class EnumMessageType
{
	const description=array('1'=>'消息','2'=>'通知');
		
	/**
     * 消息
	 * 消息。如个人对个人的消息，群消息
     */
    const chat = 1;	
		
	/**
     * 通知
	 * 通知。如加好友的请求，加群的请求等
     */
    const notification = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumMessageType","fullName":"App\\Http\\Modules\\MessageComponent\\GeneratedCodes\\Enum\\EnumMessageType","displayName":"消息类型","description":"消息的类型","items": [{"value":"1","name":"chat","displayName":"消息","description":"消息。如个人对个人的消息，群消息"},{"value":"2","name":"notification","displayName":"通知","description":"通知。如加好友的请求，加群的请求等"}]}';
	}
}
