<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message;


/**
 * MQTT消息质量
 * MQTT消息质量业界标准定义
 * 
 */
class EnumQosType
{
	const Description=array('0'=>'最多一次','1'=>'至少一次','2'=>'只有一次');
		
	/**
     * 最多一次
	 * 最多一次，消息有可能重复或丢失
     */
    const AtMostOnce = 0;	
		
	/**
     * 至少一次
	 * 至少一次，消息有可能重复
     */
    const AtLeastOnce = 1;	
		
	/**
     * 只有一次
	 * 只有一次，确保消息只到达一次
     */
    const ExactlyOnce = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
