<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-04-02 10:21:04
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message\enums;


/**
 * 用户的类型
 * 用户的类型
 * 
 */
class EnumUserType
{
	const description=array('1'=>'普通用户','4'=>'商家','16'=>'客服','64'=>'超级用户');
		
	/**
     * 普通用户
	 * 普通用户
     */
    const normal = 1;	
		
	/**
     * 商家
	 * 依靠我们平台做生意的商家，如经纪人
     */
    const merchant = 4;	
		
	/**
     * 客服
	 * 客服
     */
    const service = 16;	
		
	/**
     * 超级用户
	 * 超级用户
     */
    const superuser = 64;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumUserType","fullName":"App\\Http\\Modules\\MessageComponent\\GeneratedCodes\\Enum\\EnumUserType","displayName":"用户的类型","description":"用户的类型","items": [{"value":"1","name":"normal","displayName":"普通用户","description":"普通用户"},{"value":"4","name":"merchant","displayName":"商家","description":"依靠我们平台做生意的商家，如经纪人"},{"value":"16","name":"service","displayName":"客服","description":"客服"},{"value":"64","name":"superuser","displayName":"超级用户","description":"超级用户"}]}';
	}
}
