<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message;


/**
 * 消息类型
 * 消息的类型
 * 
 */
class EnumMessageType
{
	const Description=array('1'=>'消息','2'=>'通知');
		
	/**
     * 消息
	 * 消息。如个人对个人的消息，群消息
     */
    const Chat = 1;	
		
	/**
     * 通知
	 * 通知。如加好友的请求，加群的请求等
     */
    const Notification = 2;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
