<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-13 10:28:40
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message;


/**
 * 用户的类型
 * 用户的类型
 * 
 */
class EnumUserType
{
	const Description=array('1'=>'普通用户','4'=>'商家','16'=>'客服','64'=>'超级用户');
		
	/**
     * 普通用户
	 * 普通用户
     */
    const Normal = 1;	
		
	/**
     * 商家
	 * 依靠我们平台做生意的商家，如经纪人
     */
    const Merchant = 4;	
		
	/**
     * 客服
	 * 客服
     */
    const Service = 16;	
		
	/**
     * 超级用户
	 * 超级用户
     */
    const Superuser = 64;	
      
	public static function getDescription($key){
        return self::Description[$key];
    }
}
