<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-03-22 16:41:32
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message\enums;


/**
 * MQTT消息质量
 * MQTT消息质量业界标准定义
 * 
 */
class EnumQosType
{
	const description=array('0'=>'最多一次','1'=>'至少一次','2'=>'只有一次');
		
	/**
     * 最多一次
	 * 最多一次，消息有可能重复或丢失
     */
    const atMostOnce = 0;	
		
	/**
     * 至少一次
	 * 至少一次，消息有可能重复
     */
    const atLeastOnce = 1;	
		
	/**
     * 只有一次
	 * 只有一次，确保消息只到达一次
     */
    const exactlyOnce = 2;	
      
	public static function getDescription($key){
        return isset(self::description[$key])?self::description[$key]:'';
    }
	public static function toJSON(){
		return '{"name":"EnumQosType","fullName":"App\\Http\\Modules\\MessageComponent\\GeneratedCodes\\Enum\\EnumQosType","displayName":"MQTT消息质量","description":"MQTT消息质量业界标准定义","items": [{"value":"0","name":"atMostOnce","displayName":"最多一次","description":"最多一次，消息有可能重复或丢失"},{"value":"1","name":"atLeastOnce","displayName":"至少一次","description":"至少一次，消息有可能重复"},{"value":"2","name":"exactlyOnce","displayName":"只有一次","description":"只有一次，确保消息只到达一次"}]}';
	}
}
