<?php
//-------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：{{Enum}}.php.tt
//     生成日期：2019-02-22 18:03:22
// </auto-generated>
//------------------------------------------------------------------------------
namespace comMoerlongBL\message\enums;


/**
 * 通知的类型
 * 通知的类型
 * 
 */
class EnumNotificationType
{
	const Description=array('1'=>'加好友的请求','2'=>'加好友的请求已通过','4'=>'好友上线','8'=>'好友下线','16'=>'加群的请求','32'=>'加群的请求已通过','64'=>'群成员发生了变动','128'=>'系统通知','256'=>'转线请求','512'=>'转线请求已通过','1024'=>'转线请求被取消');
		
	/**
     * 加好友的请求
	 * 加好友的请求
     */
    const ContactAddingRequest = 1;	
		
	/**
     * 加好友的请求已通过
	 * 加好友的请求已通过
     */
    const ContactAddingRequestAgreed = 2;	
		
	/**
     * 好友上线
	 * 好友上线
     */
    const Online = 4;	
		
	/**
     * 好友下线
	 * 好友下线
     */
    const Offline = 8;	
		
	/**
     * 加群的请求
	 * 加群的请求
     */
    const ChatRoomJoinRequest = 16;	
		
	/**
     * 加群的请求已通过
	 * 加群的请求已通过
     */
    const ChatRoomJoinRequestAgreed = 32;	
		
	/**
     * 群成员发生了变动
	 * 群成员发生了变动
     */
    const ChatRoomMemberChanged = 64;	
		
	/**
     * 系统通知
	 * 系统通知
     */
    const System = 128;	
		
	/**
     * 转线请求
	 * 转线请求
     */
    const RedirectRequest = 256;	
		
	/**
     * 转线请求已通过
	 * 转线请求已通过
     */
    const RedirectRequestAgreed = 512;	
		
	/**
     * 转线请求被取消
	 * 转线请求被取消
     */
    const RedirectRequestCancelled = 1024;	
      
	public static function getDescription($key){
        return isset(self::Description[$key])?self::Description[$key]:'';
    }
}
